[package]
name = "mirror-cache"
version = "0.1.0"
authors = ["SeanChao <seanchao0804@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
redis = { version = "0.21", features = ["aio", "tokio-comp"] }
reqwest = "0.11"
thiserror = "1.0"
warp = "0.3"

[dev-dependencies]
serial_test = "*"
