[package]
name = "mirror-cache"
version = "0.1.0"
authors = ["SeanChao <seanchao0804@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
warp = "0.3"
