port: 9000
metrics_port: 9001
# log level: error / warn / info / debug / trace, default level is info
log_level: info
hot_reload: false

redis:
  url: redis://localhost

sled:
  metadata_path: cache/sled_metadata

rules:
  # GitHub-Releases
  - name: GitHub Home
    path: "/github-releases/"
    upstream: "https://github.com/"
    policy: "policy_ttl_60"

  - name: Package Version
    path: "/github-releases/git-for-windows/git/releases/download/v2.34.1.windows.1/Git-2.34.1-64-bit.exe"
    size_limit: 1 GB
    upstream: "https://github.com/git-for-windows/git/releases/download/v2.34.1.windows.1/Git-2.34.1-64-bit.exe"
    policy: "policy_ttl_60"

policies:
  - name: policy_ttl_60
    type: TTL
    metadata_db: sled
    storage: in-mem
    timeout: 60
    clean_interval: 10 # TTL cache cleanup interval, for sled only
  - name: policy_lru
    type: LRU
    metadata_db: sled
    storage: local-fs
    size: 1 GB
  - name: policy_ubuntu
    type: LRU
    metadata_db: sled
    storage: local-fs
    size: 128 MB

storages:
  - name: local-fs
    type: FS
    config:
      Fs:
        path: "cache"
  - name: in-mem
    type: MEM
    config: Mem
  - name: S3
    type: S3
    config:
      S3:
        endpoint: "http://localhost:9123"
        bucket: "cache"
