port: 9000
debug: true
url: http://localhost:9000 # url of this app

redis:
  url: redis://localhost

builtin:
  pypi_index:
    policy: "policy_ttl_60"
    upstream: "https://pypi.org/simple"
  pypi_packages:
    policy: "policy_lru_8G"
    upstream: "https://files.pythonhosted.org/packages"
  anaconda:
    policy: "policy_ttl_60"
    upstream: "https://conda-static.anaconda.org"

rules:
  - path: "unimplemented_example"
    policy: "policy_ttl_60"
    upstream: "https://upstream.org/simple/"

policies:
  - name: policy_ttl_60
    type: TTL
    path: "cache/ttl"
    timeout: 60
  - name: policy_lru_16M
    type: LRU
    size: 16777216
    path: "cache/lru"
  - name: policy_lru_8G
    type: LRU
    size: 8589934592
    path: "cache/lru"
