port: 9001
debug: true
url: https://localhost:9001
log_level: trace

redis:
  url: redis://localhost:3001

builtin:
  pypi_index:
    policy: "policy_ttl_3"
    upstream: "https://pypi.org/simple"
  pypi_packages:
    policy: "policy_lru_1k"
    upstream: "https://files.pythonhosted.org"
  anaconda:
    policy: "policy_ttl_3"
    upstream: "https://conda-static.anaconda.org"

rules: []

policies:
  - name: policy_ttl_3
    type: TTL
    path: ".cache-test/ttl"
    timeout: 3
  - name: policy_lru_1k
    type: LRU
    size: 1024
    path: ".cache-test/lru"
