port: 9000
debug: true
url: http://localhost:9000 # url of this app
# log level: error / warn / info / debug / trace, default level is info
log_level: debug

redis:
  url: redis://localhost

builtin:
  pypi_index:
    policy: "policy_ttl_60"
    upstream: "https://pypi.org/simple"
  pypi_packages:
    policy: "policy_lru_8G"
    upstream: "https://files.pythonhosted.org/packages"
  anaconda:
    policy: "policy_ttl_60"
    upstream: "https://conda-static.anaconda.org"

rules:
  - path: 'ubuntu/dists/(.*)/(.*)'
    policy: "policy_ubuntu"
    upstream: "http://archive.ubuntu.com/ubuntu/dists/$1/$2"
    id: "ubuntu"

policies:
  - name: policy_ttl_60
    type: TTL
    path: "cache/ttl"
    timeout: 60
  - name: policy_lru_8G
    type: LRU
    size: 8589934592
    path: "cache/lru"
  - name: policy_ubuntu
    type: LRU
    size: 0x2000000 # 32M
    path: cache/ubuntu
