name: PIP Test
on: push

jobs:
  build-pip_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - run: |
          cargo run &
          ./scripts/pip_test.sh torch http://localhost:9000/pypi/web/simple
      - name: mirror test
        continue-on-error: true
        run: |
          npm install -g zx
          zx ./scripts/pip_test.mjs
